### ISSUE TITLE
Formats documentation

### ISSUE THREAD

**Issue by pfusik** [Gury8/Mad-Studio#3]
I'm implementing the Mad-Studio formats in http://recoil.sourceforge.net
mad-studio-file-formats.pdf was very handy, thanks!

I have some doubts:

1. What resolution to display sprites in? (single-line vs double-line) The PDF contains the players in double-line res but the missiles in single-line.

2. *.mpl is defined to be fixed at 174 bytes. Does it mean the first byte is always 40?

3. examples/CASTLEX.AN4 doesn't conform to the format (no header).

4. *.tl4 - PDF says the first byte is height and the second is width. From the examples and code I believe it's the other way around.

**Comment by Gury8** [comment]
Hello!

1.) The P/M resolution doesn't matter, because it is set after reading file into the program.
2.) No, it is not fixed anymore. It was changed after specific request, but I forgot to update docs. This value depends on the value set in field Player height, which can be set up to 40 pixels in height.
3.) This will be checked furthermore.
4.) True, you are right, it's the other way around :) My mistake (copy/paste issue)

This is the first issue request for this program. Thank you for your investigation and keep going with your great software, including useful Recoil viewer, which I use time to time.

**Comment by Gury8** [comment]
Documentation about program formats is updated!

**Comment by Gury8** [comment]
3.) Confirmed, this file is without header and does not conform to the standards of the program. I forgot to remove it when first package was created. So I deleted it now.

**Comment by pfusik** [comment]
Thank you and good luck with your project!
